run:
  timeout: 5m

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: "ignoring Close error"
