services:
  postgres:
    container_name: "lc_badge_postgres"
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
#    ports:
#      - "5432:5432"
    volumes:
      - ./.docker/volumes/postgresql/data/:/var/lib/postgresql/data/

  redis:
    container_name: "lc_badge_redis"
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  app:
    container_name: "lc_badge_app"
    image: golang:1.21.0-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: "sleep infinity"
    environment:
      ENVIRONMENT: ${ENVIRONMENT}
      POSTGRES_DSN: ${POSTGRES_DSN}
      GOOSE_DBSTRING: ${POSTGRES_DSN}
      REDIS_OPT: ${REDIS_OPT}
      PORT: ${PORT}
      HOSTS: ${HOSTS}
      TLS_CERTIFICATES_DIR: ${TLS_CERTIFICATES_DIR}
      GIN_MODE: release
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - postgres
      - redis