// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbs

import (
	"context"
	"database/sql"
	"fmt"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

func Prepare(ctx context.Context, db DBTX) (*Queries, error) {
	q := Queries{db: db}
	var err error
	if q.insertStatsInfoStmt, err = db.PrepareContext(ctx, insertStatsInfo); err != nil {
		return nil, fmt.Errorf("error preparing query InsertStatsInfo: %w", err)
	}
	if q.updateLcStatsStmt, err = db.PrepareContext(ctx, updateLcStats); err != nil {
		return nil, fmt.Errorf("error preparing query UpdateLcStats: %w", err)
	}
	if q.userGetBySocialProviderIdStmt, err = db.PrepareContext(ctx, userGetBySocialProviderId); err != nil {
		return nil, fmt.Errorf("error preparing query UserGetBySocialProviderId: %w", err)
	}
	if q.userGetStatsByIDStmt, err = db.PrepareContext(ctx, userGetStatsByID); err != nil {
		return nil, fmt.Errorf("error preparing query UserGetStatsByID: %w", err)
	}
	if q.userNewAndParseStmt, err = db.PrepareContext(ctx, userNewAndParse); err != nil {
		return nil, fmt.Errorf("error preparing query UserNewAndParse: %w", err)
	}
	return &q, nil
}

func (q *Queries) Close() error {
	var err error
	if q.insertStatsInfoStmt != nil {
		if cerr := q.insertStatsInfoStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing insertStatsInfoStmt: %w", cerr)
		}
	}
	if q.updateLcStatsStmt != nil {
		if cerr := q.updateLcStatsStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing updateLcStatsStmt: %w", cerr)
		}
	}
	if q.userGetBySocialProviderIdStmt != nil {
		if cerr := q.userGetBySocialProviderIdStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userGetBySocialProviderIdStmt: %w", cerr)
		}
	}
	if q.userGetStatsByIDStmt != nil {
		if cerr := q.userGetStatsByIDStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userGetStatsByIDStmt: %w", cerr)
		}
	}
	if q.userNewAndParseStmt != nil {
		if cerr := q.userNewAndParseStmt.Close(); cerr != nil {
			err = fmt.Errorf("error closing userNewAndParseStmt: %w", cerr)
		}
	}
	return err
}

func (q *Queries) exec(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (sql.Result, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).ExecContext(ctx, args...)
	case stmt != nil:
		return stmt.ExecContext(ctx, args...)
	default:
		return q.db.ExecContext(ctx, query, args...)
	}
}

func (q *Queries) query(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) (*sql.Rows, error) {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryContext(ctx, args...)
	default:
		return q.db.QueryContext(ctx, query, args...)
	}
}

func (q *Queries) queryRow(ctx context.Context, stmt *sql.Stmt, query string, args ...interface{}) *sql.Row {
	switch {
	case stmt != nil && q.tx != nil:
		return q.tx.StmtContext(ctx, stmt).QueryRowContext(ctx, args...)
	case stmt != nil:
		return stmt.QueryRowContext(ctx, args...)
	default:
		return q.db.QueryRowContext(ctx, query, args...)
	}
}

type Queries struct {
	db                            DBTX
	tx                            *sql.Tx
	insertStatsInfoStmt           *sql.Stmt
	updateLcStatsStmt             *sql.Stmt
	userGetBySocialProviderIdStmt *sql.Stmt
	userGetStatsByIDStmt          *sql.Stmt
	userNewAndParseStmt           *sql.Stmt
}

func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{
		db:                            tx,
		tx:                            tx,
		insertStatsInfoStmt:           q.insertStatsInfoStmt,
		updateLcStatsStmt:             q.updateLcStatsStmt,
		userGetBySocialProviderIdStmt: q.userGetBySocialProviderIdStmt,
		userGetStatsByIDStmt:          q.userGetStatsByIDStmt,
		userNewAndParseStmt:           q.userNewAndParseStmt,
	}
}
