// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package dbs

import (
	"database/sql"
	"time"
)

type LcStat struct {
	UserID        int64
	Username      string
	EasySubmits   sql.NullInt64
	MediumSubmits sql.NullInt64
	HardSubmits   sql.NullInt64
	TotalSubmits  sql.NullInt64
	Rank          int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type User struct {
	ID       int64
	LcUserID string
}
