name: CI with Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install dependencies
        run: go mod download

      - name: Run linters with golangci-lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.61.0
          args: --timeout 5m

      - name: Install Make and Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y make docker-compose

      - name: start the application
        run: |
          make env-up
          make migrate-pgsql-up
          make app-build
          docker-compose up -d lc_badge_app